UPDATE countries SET countries_name = 'Afghanestan' WHERE countries_iso_code_3 = 'AFG';
UPDATE countries SET countries_name = 'Shqipëria' WHERE countries_iso_code_3 = 'ALB';
UPDATE countries SET countries_name = 'Dzayer' WHERE countries_iso_code_3 = 'DZA';
UPDATE countries SET countries_name = 'Hayastán' WHERE countries_iso_code_3 = 'ARM';
UPDATE countries SET countries_name = 'Österreich' WHERE countries_iso_code_3 = 'AUT';
UPDATE countries SET countries_name = 'Azərbaycan' WHERE countries_iso_code_3 = 'AZE';
UPDATE countries SET countries_name = 'Al-Bahrayn' WHERE countries_iso_code_3 = 'BHR';
UPDATE countries SET countries_name = 'Bielaruś' WHERE countries_iso_code_3 = 'BLR';
UPDATE countries SET countries_name = 'België' WHERE countries_iso_code_3 = 'BEL';
UPDATE countries SET countries_name = 'Bénin' WHERE countries_iso_code_3 = 'BEN';
UPDATE countries SET countries_name = 'Druk Yul' WHERE countries_iso_code_3 = 'BTN';
UPDATE countries SET countries_name = 'Bosnia I Hercegovína' WHERE countries_iso_code_3 = 'BIH';
UPDATE countries SET countries_name = 'Brasil' WHERE countries_iso_code_3 = 'BRA';
UPDATE countries SET countries_name = 'Bulgariya' WHERE countries_iso_code_3 = 'BGR';
UPDATE countries SET countries_name = 'Kampuchea' WHERE countries_iso_code_3 = 'KHM';
UPDATE countries SET countries_name = 'Cabo Verde' WHERE countries_iso_code_3 = 'CPV';
UPDATE countries SET countries_name = 'République Centrafricaine' WHERE countries_iso_code_3 = 'CAF';
UPDATE countries SET countries_name = 'Tchad' WHERE countries_iso_code_3 = 'TCD';
UPDATE countries SET countries_name = 'Zhōngguó' WHERE countries_iso_code_3 = 'CHN';
UPDATE countries SET countries_name = 'République du Congo' WHERE countries_iso_code_3 = 'COG';
UPDATE countries SET countries_name = 'Côte d\'Ivoire' WHERE countries_iso_code_3 = 'CIV';
UPDATE countries SET countries_name = 'Hrvatska' WHERE countries_iso_code_3 = 'HRV';
UPDATE countries SET countries_name = 'Κύπρος' WHERE countries_iso_code_3 = 'CYP';
UPDATE countries SET countries_name = 'Česko' WHERE countries_iso_code_3 = 'CZE';
UPDATE countries SET countries_name = 'Danmark' WHERE countries_iso_code_3 = 'DNK';
UPDATE countries SET countries_name = 'República Dominicana' WHERE countries_iso_code_3 = 'DOM';
UPDATE countries SET countries_name = 'Timor-Lester' WHERE countries_iso_code_3 = 'TLS';
UPDATE countries SET countries_name = 'Misr' WHERE countries_iso_code_3 = 'EGY';
UPDATE countries SET countries_name = 'Guinea Ecuatorial' WHERE countries_iso_code_3 = 'GNQ';
UPDATE countries SET countries_name = 'Iritriya' WHERE countries_iso_code_3 = 'ERI';
UPDATE countries SET countries_name = 'Eesti' WHERE countries_iso_code_3 = 'EST';
UPDATE countries SET countries_name = 'Ityop\'ia' WHERE countries_iso_code_3 = 'ETH';
UPDATE countries SET countries_name = 'Suomi' WHERE countries_iso_code_3 = 'FIN';
UPDATE countries SET countries_name = 'Guyanne française' WHERE countries_iso_code_3 = 'GUF';
UPDATE countries SET countries_name = 'Polynésie française' WHERE countries_iso_code_3 = 'PYF';
UPDATE countries SET countries_name = 'Terres australes et antarctiques françaises' WHERE countries_iso_code_3 = 'ATF';
UPDATE countries SET countries_name = 'République gabonaise' WHERE countries_iso_code_3 = 'GAB';
UPDATE countries SET countries_name = 'Sak\'art\'velo' WHERE countries_iso_code_3 = 'GEO';
UPDATE countries SET countries_name = 'Deutschland' WHERE countries_iso_code_3 = 'DEU';
UPDATE countries SET countries_name = 'Ελλάς' WHERE countries_iso_code_3 = 'GRC';
UPDATE countries SET countries_name = 'Guinée' WHERE countries_iso_code_3 = 'GIN';
UPDATE countries SET countries_name = 'Guiné-Bissau' WHERE countries_iso_code_3 = 'GNB';
UPDATE countries SET countries_name = 'Haïti' WHERE countries_iso_code_3 = 'HTI';
UPDATE countries SET countries_name = 'Magyarország' WHERE countries_iso_code_3 = 'HUN';
UPDATE countries SET countries_name = 'Ísland' WHERE countries_iso_code_3 = 'ISL';
UPDATE countries SET countries_name = 'Īrān (Islamic Republic of)' WHERE countries_iso_code_3 = 'IRN';
UPDATE countries SET countries_name = 'Al-\'Iraq' WHERE countries_iso_code_3 = 'IRQ';
UPDATE countries SET countries_name = 'Éire' WHERE countries_iso_code_3 = 'IRL';
UPDATE countries SET countries_name = 'Yisrā\'el' WHERE countries_iso_code_3 = 'ISR';
UPDATE countries SET countries_name = 'Italia' WHERE countries_iso_code_3 = 'ITA';
UPDATE countries SET countries_name = 'Nippon' WHERE countries_iso_code_3 = 'JPN';
UPDATE countries SET countries_name = 'Al-\'Urdun' WHERE countries_iso_code_3 = 'JOR';
UPDATE countries SET countries_name = 'Qazaqstan Қазақстан' WHERE countries_iso_code_3 = 'KAZ';
UPDATE countries SET countries_name = 'Tungaru' WHERE countries_iso_code_3 = 'KIR';
UPDATE countries SET countries_name = 'Chosŏn' WHERE countries_iso_code_3 = 'PRK';
UPDATE countries SET countries_name = 'Hanguk' WHERE countries_iso_code_3 = 'KOR';
UPDATE countries SET countries_name = 'Dawlat ul-Kuwayt' WHERE countries_iso_code_3 = 'KWT';
UPDATE countries SET countries_name = 'Kyrgyzstan Кыргызстан' WHERE countries_iso_code_3 = 'KGZ';
UPDATE countries SET countries_name = 'Lao' WHERE countries_iso_code_3 = 'LAO';
UPDATE countries SET countries_name = 'Latvija' WHERE countries_iso_code_3 = 'LVA';
UPDATE countries SET countries_name = 'Lubnān' WHERE countries_iso_code_3 = 'LBN';
UPDATE countries SET countries_name = 'Lietuva' WHERE countries_iso_code_3 = 'LTU';
UPDATE countries SET countries_name = 'Dhivehi Raajje' WHERE countries_iso_code_3 = 'MDV';
UPDATE countries SET countries_name = 'Muritan' WHERE countries_iso_code_3 = 'MRT';
UPDATE countries SET countries_name = 'México' WHERE countries_iso_code_3 = 'MEX';
UPDATE countries SET countries_name = 'Monaca' WHERE countries_iso_code_3 = 'MCO';
UPDATE countries SET countries_name = 'Mongol Uls Монгол Улс' WHERE countries_iso_code_3 = 'MNG';
UPDATE countries SET countries_name = 'Al-maɣréb' WHERE countries_iso_code_3 = 'MAR';
UPDATE countries SET countries_name = 'Moçambique' WHERE countries_iso_code_3 = 'MOZ';
UPDATE countries SET countries_name = 'Myanma' WHERE countries_iso_code_3 = 'MMR';
UPDATE countries SET countries_name = 'Naoero' WHERE countries_iso_code_3 = 'NRU';
UPDATE countries SET countries_name = 'Nepāl' WHERE countries_iso_code_3 = 'NPL';
UPDATE countries SET countries_name = 'Nederland' WHERE countries_iso_code_3 = 'NLD';
UPDATE countries SET countries_name = 'Nouvelle-Calédonie' WHERE countries_iso_code_3 = 'NCL';
UPDATE countries SET countries_name = 'Norge' WHERE countries_iso_code_3 = 'NOR';
UPDATE countries SET countries_name = '\'Umān' WHERE countries_iso_code_3 = 'OMN';
UPDATE countries SET countries_name = 'Pākistān' WHERE countries_iso_code_3 = 'PAK';
UPDATE countries SET countries_name = 'Panamá' WHERE countries_iso_code_3 = 'PAN';
UPDATE countries SET countries_name = 'Perú' WHERE countries_iso_code_3 = 'PER';
UPDATE countries SET countries_name = 'Polska' WHERE countries_iso_code_3 = 'POL';
UPDATE countries SET countries_name = 'Qaṭar' WHERE countries_iso_code_3 = 'QAT';
UPDATE countries SET countries_name = 'România' WHERE countries_iso_code_3 = 'ROM';
UPDATE countries SET countries_name = 'Россия' WHERE countries_iso_code_3 = 'RUS';
UPDATE countries SET countries_name = 'São Tomé e Principe' WHERE countries_iso_code_3 = 'STP';
UPDATE countries SET countries_name = 'Al-\'Arabiyyah as Sa\'ūdiyyah' WHERE countries_iso_code_3 = 'SAU';
UPDATE countries SET countries_name = 'Sénégal' WHERE countries_iso_code_3 = 'SEN';
UPDATE countries SET countries_name = 'Slovensko' WHERE countries_iso_code_3 = 'SVK';
UPDATE countries SET countries_name = 'Slovenija' WHERE countries_iso_code_3 = 'SVN';
UPDATE countries SET countries_name = 'Soomaaliya aş-Şūmāl' WHERE countries_iso_code_3 = 'SOM';
UPDATE countries SET countries_name = 'España' WHERE countries_iso_code_3 = 'ESP';
UPDATE countries SET countries_name = 'Sri Lankā' WHERE countries_iso_code_3 = 'LKA';
UPDATE countries SET countries_name = 'As-Sudan' WHERE countries_iso_code_3 = 'SDN';
UPDATE countries SET countries_name = 'Surinam' WHERE countries_iso_code_3 = 'SUR';
UPDATE countries SET countries_name = 'eSwatini' WHERE countries_iso_code_3 = 'SWZ';
UPDATE countries SET countries_name = 'Sverige' WHERE countries_iso_code_3 = 'SWE';
UPDATE countries SET countries_name = 'Suriyah' WHERE countries_iso_code_3 = 'SYR';
UPDATE countries SET countries_name = 'Tojikistan' WHERE countries_iso_code_3 = 'TJK';
UPDATE countries SET countries_name = 'Prathet Thai' WHERE countries_iso_code_3 = 'THA';
UPDATE countries SET countries_name = 'Tunes' WHERE countries_iso_code_3 = 'TUN';
UPDATE countries SET countries_name = 'Türkiye' WHERE countries_iso_code_3 = 'TUR';
UPDATE countries SET countries_name = 'Türkmenistan' WHERE countries_iso_code_3 = 'TKM';
UPDATE countries SET countries_name = 'Ukraїna' WHERE countries_iso_code_3 = 'UKR';
UPDATE countries SET countries_name = 'Al-\'Imārat Al-\'Arabiyyah Al-Muttaḥidah' WHERE countries_iso_code_3 = 'ARE';
UPDATE countries SET countries_name = 'O\'zbekiston' WHERE countries_iso_code_3 = 'UZB';
UPDATE countries SET countries_name = 'Città del Vaticano' WHERE countries_iso_code_3 = 'VAT';
UPDATE countries SET countries_name = 'Việt Nam' WHERE countries_iso_code_3 = 'VNM';
UPDATE countries SET countries_name = 'Al-Yaman' WHERE countries_iso_code_3 = 'YEM';
UPDATE countries SET countries_name = 'Srbija' WHERE countries_iso_code_3 = 'SRB';
UPDATE countries SET countries_name = 'République démocratique du Congo' WHERE countries_iso_code_3 = 'COD';
UPDATE countries SET countries_name = 'Crna Gora' WHERE countries_iso_code_3 = 'MNE';
UPDATE countries SET countries_name = 'Filasṭīn' WHERE countries_iso_code_3 = 'PSE';